spring.application.name=luyentap
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=dhkhtn
spring.profiles.active=default
#debug=true
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
